parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module

env:
  node: true
  es2020: true

plugins:
  - react
  - "@typescript-eslint"

settings:
  react:
    version: detect

rules:
  # Possible Errors
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: off
  no-constant-condition: error
  no-control-regex: error
  no-debugger: off
  no-dupe-args: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-character-class: error
  no-ex-assign: off
  no-extra-boolean-cast: error
  "@typescript-eslint/no-extra-parens":
    - error
    - all
    - ignoreJSX: all
      enforceForArrowConditionals: false
  "@typescript-eslint/no-extra-semi": error
  no-func-assign: error
  no-import-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-misleading-character-class: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-setter-return: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  # no-useless-backreference: error
  require-atomic-updates: error
  use-isnan: error
  valid-typeof: error

  # Best Practices
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this:
    - error
    - exceptMethods:
      - render
  complexity: off
  consistent-return: off
  curly: error
  default-case: error
  # default-case-last: error
  "@typescript-eslint/default-param-last": off
  dot-location: error
  dot-notation: error
  eqeqeq: error
  grouped-accessor-pairs: error
  guard-for-in: off
  max-classes-per-file: off
  no-alert: off
  no-caller: error
  no-case-declarations: error
  no-constructor-return: error
  no-div-regex: off
  no-else-return: error
  "@typescript-eslint/no-empty-function": error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coersion: off
  no-implicit-globals: off
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: off
  no-lone-blocks: off
  no-loop-func: error
  "@typescript-eslint/no-magic-numbers": off
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: off
  no-octal-escape: off
  no-param-reassign: off
  no-proto: error
  no-redeclare: error
  no-restricted-properties: off
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: off
  "@typescript-eslint/no-unused-expressions": error
  no-unused-labels: error
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: off
  no-with: error
  prefer-named-capture-group: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  radix:
    - error
    - as-needed
  # "@typescript-eslint/require-await": error
  require-await: error
  require-unicode-regexp: error
  vars-on-top: off
  wrap-iife:
    - error
    - inside
  yoda: error

  # Strict Mode
  strict: error

  # Variables
  init-declarations: off
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow:
    - error
    - allow:
      - err
      - e
  no-shadow-restricted-names: off
  no-undef: error
  no-undef-init: error
  no-undefined: off
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-use-before-define":
    - error
    - functions: false

  # Node.js and CommonJS
  callback-return: error
  global-require: off
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: off
  no-process-exit: off
  no-restricted-modules: off
  no-sync: off

  # Stylistic Issues
  array-bracket-newline: off
  array-bracket-spacing: error
  array-element-newline: off
  block-spacing: error
  "@typescript-eslint/brace-style":
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
    - properties: never
  capitalized-comments: off
  comma-dangle:
    - error
    - always-multiline
  "@typescript-eslint/comma-spacing": error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  "@typescript-eslint/indent":
    - error
    - tab
  "@typescript-eslint/func-call-spacing": error
  func-name-matching: off
  func-names: error
  func-style:
    - error
    - declaration
  function-paren-newline:
    - error
    - consistent
  id-blacklist: off
  id-length: off
  id-match: off
  implicit-arrow-linebreak: error
  indent:
    - error
    - tab
    - SwitchCase: 1
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: off
  linebreak-style: error
  lines-around-comments: off
  lines-between-class-members: error
  max-depth: off
  max-len: off
  max-lines: off
  max-lines-per-function: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: error
  multiline-comment-style:
    - error
    - separate-lines
  multiline-ternary: off
  new-cap: error
  new-parens: error
  newline-per-chained-call: off
  "@typescript-eslint/no-array-constructor": error
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: off
  no-mixed-spaces-and-tabs: error
  no-multi-assign: off
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
  padding-line-between-statements: off
  prefer-exponentiation-operator: error
  prefer-object-spread: error
  quote-props:
    - error
    - as-needed
  "@typescript-eslint/quotes": error
  "@typescript-eslint/semi":
    - error
    - never
  semi-spacing: error
  semi-style: error
  sort-keys: off
  sort-vars: off
  space-before-blocks: off
  "@typescript-eslint/space-before-function-paren":
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-confusing-arrow: off
  no-const-assign: error
  "@typescript-eslint/no-dupe-class-members": error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-exports: off
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  "@typescript-eslint/no-useless-constructor": error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring:
    - error
    - array: false
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  rest-spread-spacing: error
  sort-imports: off
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error

  # TypeScript
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type": error
  # "@typescript-eslint/await-thenable": error
  "@typescript-eslint/ban-ts-comment": error
  "@typescript-eslint/ban-types": error
  "@typescript-eslint/class-literal-property-style": off
  "@typescript-eslint/consistent-type-assertions": error
  "@typescript-eslint/consistent-type-definitions": error
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/explicit-member-accessibility":
    - error
    - accessibility: no-public
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: "none"
  "@typescript-eslint/member-ordering": off
  "@typescript-eslint/naming-convention": error
  # "@typescript-eslint/no-base-to-string": error
  "@typescript-eslint/no-dynamic-delete": error
  "@typescript-eslint/no-empty-interface": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-extra-non-null-assertion": error
  "@typescript-eslint/no-extraneous-class": error
  # "@typescript-eslint/no-floating-promises": error
  "@typescript-eslint/no-for-in-array": error
  # "@typescript-eslint/no-implied-eval": error
  "@typescript-eslint/no-inferrable-types": error
  "@typescript-eslint/no-misused-new": error
  # "@typescript-eslint/no-misused-promises": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-non-null-asserted-optional-chain": error
  "@typescript-eslint/no-non-null-assertion": error
  "@typescript-eslint/no-parameter-properties": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-this-alias": error
  # "@typescript-eslint/no-throw-literal": error
  "@typescript-eslint/no-type-alias": error
  # "@typescript-eslint/no-unnecessary-boolean-literal-compare": error
  # "@typescript-eslint/no-unnecessary-condition": error
  # "@typescript-eslint/no-unnecessary-qualifier": error
  # "@typescript-eslint/no-unnecessary-type-arguments": error
  # "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-unsafe-call": off
  "@typescript-eslint/no-unsafe-member-access": off
  "@typescript-eslint/no-unsafe-return": off
  # "@typescript-eslint/no-unused-vars-experimental": error
  "@typescript-eslint/no-var-requires": error
  "@typescript-eslint/prefer-as-const": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-function-type": error
  # "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/prefer-namespace-keyword": error
  # "@typescript-eslint/prefer-nullish-coalescing": error
  "@typescript-eslint/prefer-optional-chain": error
  # "@typescript-eslint/prefer-readonly": error
  # "@typescript-eslint/prefer-readonly-parameter-types": error
  # "@typescript-eslint/prefer-regexp-exec": error
  # "@typescript-eslint/prefer-string-starts-ends-with": error
  # "@typescript-eslint/promise-function-async": error
  # "@typescript-eslint/require-array-sort-compare": error
  # "@typescript-eslint/restrict-plus-operands": error
  # "@typescript-eslint/restrict-template-expressions": error
  # "@typescript-eslint/strict-boolean-expressions": error
  # "@typescript-eslint/switch-exhaustiveness-check": error
  "@typescript-eslint/triple-slash-reference": error
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/typedef": off
  "@typescript-eslint/unbound-method": off
  "@typescript-eslint/unified-signatures": off

  # React
  react/boolean-prop-naming: off
  react/button-has-type: error
  react/default-props-match-prop-types: error
  react/destructuring-assignment: off
  react/display-name: off
  react/forbid-component-props: off
  react/forbid-dom-props: off
  react/forbid-elements: off
  react/forbid-prop-types: error
  react/forbid-foreign-prop-types: error
  react/no-access-state-in-setstate: off
  react/no-array-index-key: error
  react/no-children-prop: error
  react/no-danger: off
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-is-mounted: error
  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  react/no-set-state: off
  react/no-typos: error
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prefer-stateless-function: off
  react/prop-types: error
  react/react-in-jsx-scope: error
  react/require-default-props: off
  react/require-optimization: off
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: off
  react/sort-prop-types: error
  react/void-dom-elements-no-children: error

  # React > JSX
  react/jsx-boolean-value: error
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-filename-extension:
    - error
    - extensions:
      - jsx
      - tsx
  react/jsx-first-prop-new-line: error
  react/jsx-handler-names: error
  react/jsx-indent:
    - error
    - tab
  react/jsx-indent-props:
    - error
    - tab
  react/jsx-key: error
  react/jsx-max-props-per-line:
    - error
    - maximum: 2
  react/jsx-no-bind: off
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-literals: off
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-one-expression-per-line: off
  react/jsx-curly-brace-presence: error
  react/jsx-pascal-case: error
  react/jsx-sort-props: off
  react/jsx-tag-spacing: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
